# Generated by Django 3.1.1 on 2020-09-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
